---
title: "Untitled"
format: 
    html:
        self-contained: true
editor: visual

execute:
  echo: false
---

```{r}
library(r2d3)
```

```{r}
dates <- seq(as.Date("2023-06-29"), as.Date("2023-08-28"), by="days")

ojs_define(dts = dQuote(dates))
```

```{r}
#| label: word-count-data
words <- c(800, 700, 600)
wordcount <- data.frame(day=(dates), words=c(words, rep(0, 61-length(words))))

ojs_define(wordcountdata = wordcount)
```

```{r}
#| label: pomodoro-data
sessions <- c(8, 7, 6)
pomodoro <- data.frame(day=(dates), sessions=c(sessions, rep(-2, 61-length(sessions))))

ojs_define(pomodorodata = pomodoro)
```

```{ojs}
wordcountdataParsed = transpose(wordcountdata)
//wordcountdataParsed = transpose(wordcountdata).map(({day, ...rest}) => {
//  return {
//    day: new Date(day),
//    ...rest
//  };
//})

Plot.plot({
  x: {
    label: null
  },
  y: {
    grid: true,
    label: "Word Count"
  },
  marks: [
    Plot.rectY(wordcountdataParsed,
    {x: "day", 
    interval: d3.utcDay, 
    y: "words"})
    ]
})

// https://observablehq.com/d/146613c19e64e656
```

```{ojs}
pomodorodataParsed = transpose(pomodorodata)

//pomodorodataParsed = transpose(pomodorodata).map(({day, ...rest}) => {
//  return {
//    day: new Date(day),
//    ...rest
//  };
//})

Plot.plot({
  x: {
    label: null
    },
  y: {
    grid: false,
    ticks: false,
    label: "Word Count",
    domain: [0,10]
  },
  marks: [
  Plot.ruleY([0], { stroke: '#555' }),
    Plot.dot(pomodorodataParsed,
      Plot.stackY
      ({
      x: "day", 
      interval: d3.utcDay, 
      y: "sessions",
      r: 6,
      fill: true})
      )
    ]
})
```

```{r}
#| output: false

library(readr)
library(dplyr)

co2 = read_csv("co2_mm.csv")  %>% 
  group_by(year) %>% 
  summarize(max = max(average))

ojs_define(co2data = co2)
```

```{ojs}
yearlyChart = Plot.plot({
  marks: [
    Plot.line(transpose(co2data), 
      {x: "year", y: "max"}, 
      { stroke: "black" }
    )
  ]}
)
```

```{ojs}
data2 = {
  const co2data = await FileAttachment("co2_mm.csv")
    .csv({ typed: true } );
  return co2data.map(d => { 
    d["decimal date"] = Number(d["decimal date"]);
    d.average = Number(d.average); 
    return d; 
  });
}
Plot.plot({
  marks: [
    Plot.line(data2, 
      { x: "decimal date", y: "average"}, 
      { stroke: "black" }
    )
  ]
})
```
